---
- include_tasks: setup-RedHat_postgres.yml
  when: (ansible_os_family == 'RedHat' or ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "yum")

- include_tasks: setup-Debian_postgres.yml
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- name: deploy postgres backup script
  ansible.builtin.template:
    src: templates/postgres_backup.sh.j2
    dest: /usr/local/postgres_backup.sh
    owner: root
    group: root
    mode: '0755'

- name: /etc/systemd/system/postgresql_backup.timer
  ansible.builtin.template:
    src: postgres_backup.timer.j2
    dest: /etc/systemd/system/postgres_backup.timer
    owner: root
    group: root
    mode: '0644'

- name: /etc/systemd/system/postgres_backup.service
  ansible.builtin.template:
    src: postgres_backup.service.j2
    dest: /etc/systemd/system/postgres_backup.service
    owner: root
    group: root
    mode: '0644'

- name: enable, reload, start postgres backup timer
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    daemon_reload: true
    name: postgres_backup.timer

- name: enable, reload postgres backup service
  ansible.builtin.systemd_service:
    enabled: true
    name: postgres_backup.service

- name: create postgres backup dir
  ansible.builtin.file:
    path: /mnt/backup
    owner: postgres
    group: postgres
    mode: '744'
    state: directory

- name: create postgres backup log
  ansible.builtin.file:
    path: /mnt/backup/postgres_backup_log
    owner: postgres
    group: postgres
    mode: '744'
    state: touch
