---
collections:
  - name: community.general
    version: 10.3.1
  - name: awx.awx
    version: 24.6.1
  - name: freeipa.ansible_freeipa
    version: 1.14.5
  - name: ansible.posix
    version: 1.6.2
  - name: community.postgresql
    version: 3.10.2
  - name: pfsensible.core
    version: 0.6.2
