---
- include_tasks: RedHat.yml
  when: ( ansible_os_family == 'RedHat' or ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "yum")

- include_tasks: Debian.yml
  when: (ansible_distribution == "Debian" )

- include_tasks: Ubuntu.yml
  when: (ansible_distribution == "Ubuntu" )
