---
- hosts: localhost
  tasks:

  # Obtain information about a Content View and its versions
  - name: Find all CVs
    theforeman.foreman.resource_info:
      server_url: "{{ satellite_server_url }}"
      username: "{{ satellite_username }}"
      password: "{{ satellite_password }}"
      validate_certs: "{{ satellite_validate_certs }}"
      organization: "{{ satellite_organization}}"
      resource: content_views
      search: 'name="RHEL9"'
    register: raw_list_cvs

  - debug:
      var: raw_list_cvs.resources

  - debug:
      var: raw_list_cvs.resources[0].versions

  - name:
    set_fact:
      list_all_cvs: "{{ raw_list_cvs['resources'] | json_query(jmesquery) | list }}"
    vars: 
      jmesquery: "[*].{name: name, composite: composite, id: id}"

  - debug:
      var: list_all_cvs

  - name: Extract list of content views
    set_fact:
            #      sat6_content_views_list: "{{ sat6_content_views_list | default(omit) }} + ['{{ item.name }}' ]"
      sat6_content_views_list: "['{{ item.name }}' ]"
    loop: "{{ list_all_cvs | reject('search', 'Default_Organization_View') | list }}"
    when: item.composite == false

  - debug:
      var: sat6_content_views_list

  - debug:
      var: "sat6_content_views_list | list }}"


  - name: Publish content
    theforeman.foreman.content_view_version:
      server_url: "{{ satellite_server_url }}"
      username: "{{ satellite_username }}"
      password: "{{ satellite_password }}"
      organization: "{{ satellite_organization }}"
      validate_certs: "{{ satellite_validate_certs }}"
      content_view: "{{ item }}"
      description: "{{ sat_publish_description }}"
      lifecycle_environments:
        - Library
        - Lab
        - Stage
        - Prod
          #        - "{{ sat_env_name }}"
    loop: "{{ sat6_content_views_list | list }}"
    loop_control:
      loop_var: "item"
    register: cv_publish_sleeper

#   # Obtain more details about all versions of a specific Content View
#   - name: "find content view versions of {{ content_views }}"
#     theforeman.foreman.resource_info:
#       server_url: "{{ satellite_server_url }}"
#       username: "{{ satellite_username }}"
#       password: "{{ satellite_password }}"
#       validate_certs: "{{ satellite_validate_certs }}"
#       organization: "{{ satellite_organization}}"
#       resource: content_view_versions
#       params:
#         content_view_id: "{{ cvs.resources[0].id }}"
#     register: cvvs
# 
#   - debug:
#       var: cvvs
# 
#   - debug:
#       var: cvvs.resources

