---
- name: Converge
  hosts: all
  become: true
  gather_facts: yes
  vars_files:
    - ../../defaults/main.yml
  #vars:
  #  delete_puppet_ssl_dir: false
  #  apt_purge: false
  #  yum_purge: false
  #  run_puppet_agent: false
  #  fix_hosts: false
  #  offline_rpmfile: false
  #  offline_ubuntu_debfile: false
  #  offline_debain_debfile: false
  #  online_rpmfile: true
  #  online_ubuntu_debfile: true
  #  online_debian_debfile: true
  #  fix_apt_missing: false


  tasks:
    - name: "Include ansible_role_puppet_server"
      include_role:
        name: "ansible_role_puppet_server"

  #roles:
    #- role: habbis.ansible_role_puppet_server
