---
- name: Add gitlab runner GPG key.
  rpm_key:
    key: "{{ puppet_dnf_gpg_key }}"
    state: present

- name: /etc/yum.repos.d/puppet8-release.repo
  ansible.builtin.template:
    src: puppet8-release.repo.j2
    dest: /etc/yum.repos.d/puppet8-release.repo
    mode: '0644'

- name: Install the dnf versionlock plugin
  ansible.builtin.dnf:
    name:
      - python3-dnf-plugin-versionlock
    state: installed

- name: install puppetserver and puppet-agent
  ansible.builtin.yum:
    name:
      - "puppetserver-{{ puppet_server_version }}-1"
      - "puppet-agent-{{ puppet_agent_version }}-1"
    state: present

- name: Prevent puppet-agent from being updated
  community.general.dnf_versionlock:
    state: present
    name:
      - "puppet-agent-{{ puppet_agent_version }}-1"
