---
- name: copy jenkins lts key
  ansible.builtin.copy:
    src: files/debian/debian_lts_jenkins.io.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    owner: root
    group: root
    mode: '0644'
  when: jenkins_lts

- name: copy jenkins lts apt conf
  ansible.builtin.copy:
    src: files/debian/debian_lts_jenkins.list
    dest: /etc/apt/sources.list.d/jenkins.list
    owner: root
    group: root
    mode: '0644'
  when: jenkins_lts

- name: copy jenkins weekly key
  ansible.builtin.copy:
    src: files/debian/debian_weekly_jenkins.io.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    owner: root
    group: root
    mode: '0644'
  when: jenkins_weekly

- name: copy jenkins weekly apt conf
  ansible.builtin.copy:
    src: files/debian/debian_lts_jenkins.list
    dest: /etc/apt/sources.list.d/jenkins.list
    owner: root
    group: root
    mode: '0644'
  when: jenkins_weekly

- name: apt update for ubuntu
  command: apt-get update -y 
  when: (ansible_distribution == "Ubuntu")
  

- name: install jenkins
  ansible.builtin.apt:
    pkg:
    - fontconfig
    - openjdk-11-jre
    - jenkins
    update_cache: yes

- name: start, enable jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes
  ignore_errors: yes