---

- name: setup alerta
  hosts: k3s-test
  gather_facts: yes
  #remote_user: root
  remote_user: ansible
  become: yes
  #vars_files:
  #  - secrets/vault.yml


  roles:
    - {role: alerta_server_setup, tags: ["alerta_setup"]}
