---

- name: setup postgres server
  hosts: postgres
  gather_facts: yes
  remote_user: ansible
  #remote_user: root
  become: yes
  #vars_files:
  #  - secrets/vault.yml

  roles:
    - role: postgresql

