---

- name: postgres_deploy.yml | All roles
  hosts: postgres
  gather_facts: yes
  remote_user: ansible
  become: yes
  vars_files:
    - secrets/vault.yml


  roles:
    - {role: hf_postgresql_deploy }
    - {role: firewalld_postgres }
