---

- name: setup puppet server
  hosts: puppet
  gather_facts: yes
  remote_user: ansible
  become: true
  #vars_files:
  #  - secrets/vault.yml
  vars:
    - puppet_server: hf-puppet1.dc1.ncop.no
    - debian_debfile: openvox8-release-debian13.deb
    - rpmfile_release: openvox8-release-el-9.noarch.rpm
    - fix_hosts: true


  roles:
    - puppet_server

  environment:
    http_proxy: http://hf-proxy.no.habbfarm.net:8888
    https_proxy: http://hf-proxy.no.habbfarm.net:8888
