---

- name: standard_setup.yml | All roles
  hosts: all
  gather_facts: yes
  remote_user: ansible
  #remote_user: root
  become: yes
  #vars_files:
  #  - secrets/vault.yml

  roles:
    - {role: standard_setup, tags: ["standard_setup"]}

  environment:
    http_proxy: http://hf-proxy.no.habbfarm.net:8888
    https_proxy: http://hf-proxy.no.habbfarm.net:8888
