#! /usr/bin/env python3
"""
python create a new ansible playbook
"""
from __future__ import print_function
import argparse
import os
from os.path import exists as file_exists

def main():
    arg_parser  = argparse.ArgumentParser(description=__doc__)
    arg_parser.add_argument("-n", "--name", dest="new_playbook_name", help="name of new playbook and variable folder for that playbook",required=True)

     # We parse the args here to do some additional
    # obscure checks
    parsed_args = arg_parser.parse_args()

    template_playbook = "template-play"
    new_playbook = parsed_args.new_playbook_name


    os.chdir('../../plays')
    # create new playbook
    if file_exists(f"{new_playbook}.yml"):
        print(f"The playbook {new_playbook}.yml exists")
        exit()
    else: 
        with open(f"{template_playbook}.yml", "r+") as file1, open(f"{new_playbook}.yml", "w") as file2:
             file_read = file1.read()
             replace_txt = file_read.replace("template-play.yml", f"{new_playbook}.yml")
             file2.write(replace_txt)
    if os.path.isdir(f"../group_vars/{new_playbook}"):
         print(f"The variable dir {new_playbook} exists")
         exit()
    else:
        os.chdir('../group_vars')
        # create variable dir
        os.mkdir(f"{new_playbook}")
        os.chdir(f'../group_vars/{new_playbook}')
        with open(f"{new_playbook}.yml", "w") as file:
             file.write("---")

if __name__ == "__main__":
    main()
