---
- name: Converge
  hosts: all
  become: true
  gather_facts: yes
  #vars_files:
  #  - ../../defaults/main.yml
  #vars:


  tasks:
    - name: "Include hf_patching"
      include_role:
        name: "hf_patching"

  #roles:
    #- role: habbis.hf_patching
